import { readFile, writeFile, unlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import { createCanvas } from 'canvas';
import { extractImageTextAuto } from './documentTextExtractor.js';
import type { OcrResult } from './types.js';

// pdfjs-dist ships its own built-in Node canvas factory, but it's hardcoded to
// `require("@napi-rs/canvas")` internally for the scratch canvases it creates
// when compositing raster image XObjects onto the page (e.g. a scanned page
// saved as a full-page JPEG/PNG) — mixing that with the "canvas" (node-canvas)
// instance we create for the page's own canvas throws "Image or Canvas
// expected" as soon as pdfjs tries to draw one library's canvas object through
// the other's drawImage. Overriding the *class* (not instance — pdfjs
// constructs it itself via `new CanvasFactory({ownerDocument, enableHWA})`,
// keyed as `CanvasFactory`, not `canvasFactory`) makes every canvas pdfjs
// creates come from the same "canvas" library our own code uses.
class NodeCanvasFactory {
  create(width: number, height: number) {
    if (width <= 0 || height <= 0) {
      throw new Error('Invalid canvas size');
    }
    const canvas = createCanvas(width, height);
    return { canvas, context: canvas.getContext('2d') };
  }
  reset(canvasAndContext: { canvas: ReturnType<typeof createCanvas> }, width: number, height: number) {
    if (width <= 0 || height <= 0) {
      throw new Error('Invalid canvas size');
    }
    canvasAndContext.canvas.width = width;
    canvasAndContext.canvas.height = height;
  }
  destroy(canvasAndContext: {
    canvas: ReturnType<typeof createCanvas> | null;
    context: unknown;
  }) {
    if (canvasAndContext.canvas) {
      canvasAndContext.canvas.width = 0;
      canvasAndContext.canvas.height = 0;
    }
    canvasAndContext.canvas = null;
    canvasAndContext.context = null;
  }
}

async function extractEmbeddedText(
  doc: Awaited<ReturnType<typeof getDocument>['promise']>
): Promise<string> {
  const pageTexts: string[] = [];
  for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber++) {
    const page = await doc.getPage(pageNumber);
    const content = await page.getTextContent();
    const pageText = content.items
      .map((item) => ('str' in item ? item.str : ''))
      .join(' ');
    pageTexts.push(pageText);
  }
  return pageTexts.join('\n');
}

// A scanned/photocopied document saved as PDF (e.g. a Liquidation) has no
// embedded text layer — rasterize each page to a PNG (scale 2.0 for OCR
// legibility) and run it through the same engine-priority OCR path used for
// plain image uploads, reusing that logic rather than duplicating it.
async function extractScannedPdfText(
  doc: Awaited<ReturnType<typeof getDocument>['promise']>
): Promise<OcrResult> {
  const pageTexts: string[] = [];
  const confidences: number[] = [];

  for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber++) {
    const page = await doc.getPage(pageNumber);
    const viewport = page.getViewport({ scale: 2.0 });
    const canvas = createCanvas(viewport.width, viewport.height);
    const context = canvas.getContext('2d');
    await page.render({
      canvasContext: context as unknown as CanvasRenderingContext2D,
      canvas: canvas as unknown as HTMLCanvasElement,
      viewport,
    }).promise;

    const tempPath = path.join(tmpdir(), `pdf-page-${randomUUID()}.png`);
    await writeFile(tempPath, canvas.toBuffer('image/png'));
    try {
      const result = await extractImageTextAuto(tempPath);
      pageTexts.push(result.text);
      confidences.push(result.confidence);
    } finally {
      await unlink(tempPath);
    }
  }

  const confidence =
    confidences.length > 0 ? confidences.reduce((a, b) => a + b, 0) / confidences.length : 0;
  return { text: pageTexts.join('\n'), confidence };
}

// Born-digital PDFs (generated by the customs system, not scanned) carry an
// embedded text layer that pdfjs can read directly — no OCR needed, and the
// result is effectively exact (confidence 1.0), per design spec §3.1.
// Scanned PDFs (no embedded text layer) fall back to rasterize-then-OCR.
export async function extractPdfText(filePath: string): Promise<OcrResult> {
  const data = new Uint8Array(await readFile(filePath));
  const doc = await getDocument({ data, CanvasFactory: NodeCanvasFactory } as Parameters<
    typeof getDocument
  >[0]).promise;

  const embeddedText = await extractEmbeddedText(doc);
  if (embeddedText.trim().length > 0) {
    return { text: embeddedText, confidence: 1.0 };
  }

  return extractScannedPdfText(doc);
}
