import { readFile } from 'node:fs/promises';
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import type { OcrResult } from './types.js';

// Born-digital PDFs (generated by the customs system, not scanned) carry an
// embedded text layer that pdfjs can read directly — no OCR needed, and the
// result is effectively exact (confidence 1.0), per design spec §3.1.
export async function extractPdfText(filePath: string): Promise<OcrResult> {
  const data = new Uint8Array(await readFile(filePath));
  const doc = await getDocument({ data }).promise;

  const pageTexts: string[] = [];
  for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber++) {
    const page = await doc.getPage(pageNumber);
    const content = await page.getTextContent();
    const pageText = content.items
      .map((item) => ('str' in item ? item.str : ''))
      .join(' ');
    pageTexts.push(pageText);
  }

  return { text: pageTexts.join('\n'), confidence: 1.0 };
}
